Repository pimcore/demo, pull requests merged in 2022-10, with the labels that each got.

#358 [Task]: Add Intl component
  composer.json
Labels: Task

#365 [Improvement]: Replace childs with children in all data object layouts
  .env
  dump/data-1-settings_store.sql
  var/classes/customlayouts/custom_definition_CarReview.php
  var/classes/customlayouts/custom_definition_CarTodo.php
  var/classes/definition_AccessoryPart.php
  var/classes/definition_BodyStyle.php
  var/classes/definition_Car.php
  var/classes/definition_Category.php
  var/classes/definition_Customer.php
  var/classes/definition_CustomerSegment.php
  var/classes/definition_CustomerSegmentGroup.php
  var/classes/definition_Event.php
  var/classes/definition_FilterDefinition.php
  var/classes/definition_LinkActivityDefinition.php
  var/classes/definition_Manufacturer.php
  var/classes/definition_News.php
  var/classes/definition_OfferToolCustomProduct.php
  var/classes/definition_OfferToolOffer.php
  var/classes/definition_OfferToolOfferItem.php
  var/classes/definition_OnlineShopOrder.php
  var/classes/definition_OnlineShopOrderItem.php
  var/classes/definition_OnlineShopTaxClass.php
  var/classes/definition_OnlineShopVoucherSeries.php
  var/classes/definition_OnlineShopVoucherToken.php
  var/classes/definition_SsoIdentity.php
  var/classes/definition_TermSegmentBuilderDefinition.php
  var/classes/fieldcollections/FilterCategory.php
  var/classes/fieldcollections/FilterCategoryMultiselect.php
  var/classes/fieldcollections/FilterInputfield.php
  var/classes/fieldcollections/FilterMultiRelation.php
  var/classes/fieldcollections/FilterMultiSelect.php
  var/classes/fieldcollections/FilterMultiSelectFromMultiSelect.php
  var/classes/fieldcollections/FilterNumberRange.php
  var/classes/fieldcollections/FilterNumberRangeSelection.php
  var/classes/fieldcollections/FilterRelation.php
  var/classes/fieldcollections/FilterSelect.php
  var/classes/fieldcollections/FilterSelectFromMultiSelect.php
  var/classes/fieldcollections/NewsCars.php
  var/classes/fieldcollections/NewsLinks.php
  var/classes/fieldcollections/NewsText.php
  var/classes/fieldcollections/OrderByFields.php
  var/classes/fieldcollections/OrderPriceModifications.php
  var/classes/fieldcollections/PaymentInfo.php
  var/classes/fieldcollections/PricingRule.php
  var/classes/fieldcollections/SimilarityField.php
  var/classes/fieldcollections/TaxEntry.php
  var/classes/fieldcollections/VoucherTokenTypePattern.php
  var/classes/fieldcollections/VoucherTokenTypeSingle.php
  var/classes/objectbricks/Bodywork.php
  var/classes/objectbricks/Dimensions.php
  var/classes/objectbricks/Engine.php
  var/classes/objectbricks/OAuth1Token.php
  var/classes/objectbricks/OAuth2Token.php
  var/classes/objectbricks/PaymentProviderPayPalSmartButton.php
  var/classes/objectbricks/SaleInformation.php
  var/classes/objectbricks/Transmission.php
Labels: Improvement

#363 [Events] Set XMLHttpRequest header for vue response
  public/static/js/vue-app.js
Labels: Bug

#367 Remove separate PHP debug container
  .docker/nginx.conf
  docker-compose.yaml
Labels: Task

#359 [Task]: Use the correct path for Presta/sitemap-bundle v3 routing.yaml
  config/routes/presta_sitemap.yaml
Labels: Task

#366 [Task]: Updating Nginx conf to fix home page static page generation
  .docker/nginx.conf
Labels: Task

#368 Added core bundles to bundles.php
  config/bundles.php
  var/config/extensions.php
Labels: Task

#369 docker-compose: use new docker tags
  .docker/nginx.conf
  .github/workflows/pimcore-demo.yml
  README.md
  docker-compose.yaml
Labels: Task
