Repository pimcore/demo, pull requests merged in 2022-09, with the labels that each got.

#348 Fix expected type of $callable
  src/Website/Tool/ForceInheritance.php
Labels: Bug

#349 [Task]: Remove wkhtmltopdf web2print settings from dump
  dump/data-1-settings_store.sql
Labels: Task

#351 Clean up the custom layout dump
  dump/data-1-custom_layouts.sql
Labels: Task

#355 [Improvement]: consistently use .yaml not .yml
  config/routes.yaml
  config/routes/dev/routes.yaml
  var/config/system.template.yaml
Labels: Improvement, dependencies

#357 Change the path of routing yaml
  config/routes.yaml
  config/routes/dev/routes.yaml
Labels: Task
