Repository pimcore/demo, pull requests merged in 2022-04, with the labels that each got.

#304 Action for testing project creation
  .github/workflows/pimcore-demo.yml
Labels: Task

#306 Fix PHP-FPM status/ping routes in nginx config
  .docker/nginx.conf
Labels: Bug

#308 added favicon.ico
  public/favicon.ico
Labels: Improvement

#307 Content Security Policy - Disable csp for opcache status window
  config/config.yaml
Labels: Bug

#309 Cleanup docker-compose.yaml
  docker-compose.yaml
Labels: Bug
