Repository pimcore/demo, pull requests merged in 2023-02, with the labels that each got.

#407 Refactor Authentication
  config/packages/security.yaml
  src/EventListener/AuthenticationLoginListener.php
Labels: Task

#402 [Task] Enabled PimcoreSimpleBackendSearchBundle in bundles.php file
  config/bundles.php
  dump/data-0-bootstrap.sql
  dump/data-1-settings_store.sql
Labels: Task

#403 [Bug]: Fix using query instead of attributes
  src/Controller/Web2printController.php
Labels: Bug

#411 Add symfony/dotenv requirement
  composer.json
Labels: Task

#412 [Task]: Add ApplicationLoggerBundle to demo
  config/bundles.php
  dump/data-0-bootstrap.sql
  dump/data-1-settings_store.sql
Labels: Task

#395 Replace SensioFrameworkExtraBundle with PHP 8 attribute
  src/Controller/AccountController.php
  src/Controller/ContentController.php
  src/Controller/DefaultController.php
Labels: Task

#414 [Task]: Disallow php-http/discovery plug in
  composer.json
Labels: Task

#415 Fix undefined method getObject in Document\Link
  templates/layouts/layout.html.twig
Labels: Bug

#409 [Improvement]: Replace plugins with event listener
  public/static/js/startup.js
Labels: Improvement

#410 Remove the usage of SSOAware interface
  src/Model/Customer.php
Labels: Task

#418 Enable Personalization Bundle in demo and Change namespace accordingly
  config/bundles.php
  dump/data-0-bootstrap.sql
  dump/data-1-settings_store.sql
  src/Document/Areabrick/PersonalizedProductTeaser.php
  src/Services/SegmentTrackingHelperService.php
Labels: Task

#420 [Task]: Enable PimcoreWebToPrintBundle in bundles.php
  config/bundles.php
  dump/data-0-bootstrap.sql
  dump/data-0-update.sql
  dump/data-1-settings_store.sql
Labels: Task

#427 Fix path of installation file in dump
  dump/create-dump.php
Labels: Bug

#423 docker-compose: use PHP 8.2 images
  .github/workflows/pimcore-demo.yml
  README.md
  docker-compose.yaml
Labels: Task

#428 Upgrade to latest jQuery version
  templates/layouts/layout.html.twig
  templates/layouts/print_catalog.html.twig
Labels: Task

#417 [Task]: Change Namespaces and config after Sitemap and Redirect extraction into SEO Bundle.
  config/config.yaml
  dump/data-0-bootstrap.sql
  src/Sitemaps/CategoryGenerator.php
  src/Sitemaps/NewsGenerator.php
  src/Sitemaps/Processors/AbsoluteURLProcessor.php
  src/Sitemaps/ProductGenerator.php
Labels: Improvement

#424 Enable GoogleMarketingBundle bundle
  config/bundles.php
  config/config.yaml
  dump/data-1-settings_store.sql
Labels: Task
