Repository pimcore/demo, pull requests merged in 2023-04, with the labels that each got.

#453 [Task]: Add config for write targets
  .env
  config/config.yaml
Labels: Task

#454 [Improvement]: rename master to main
  CONTRIBUTING.md
  dump/data-0-bootstrap.sql
  dump/data-1-documents_page.sql
  dump/data-1-documents_printpage.sql
  dump/data-1-documents_snippet.sql
Labels: Improvement

#457 Adapt Storage location improvements
  config/config.yaml
Labels: Task

#458 Require pimcore/web-to-print-bundle
  composer.json
Labels: Task

#461 Remove `AbstractSsoIdentity` as parentClass
  var/classes/definition_SsoIdentity.php
Labels: Task

#463 [Bug]: Fix typo in setting store sql about web2print bundle
  dump/data-1-settings_store.sql
Labels: Bug

#464 [Task] Adapt changes from bundle extraction
  src/Command/DataCommand.php
  src/Controller/AccountController.php
  src/Controller/PaymentController.php
  src/Controller/ProductController.php
  src/Controller/Web2printController.php
  src/Ecommerce/Cart/PriceModificator/Shipping.php
  src/EventListener/CheckoutEventListener.php
Labels: Task

#465 [Task] Enable PimcoreNewsletterBundle in config/bundles.php
  composer.json
  config/bundles.php
  config/config.yaml
  dump/data-0-bootstrap.sql
  dump/data-1-settings_store.sql
  dump/data-1-users_permission_definitions.sql
Labels: Task

#467 Enable AdminBundle: require pimcore/admin-ui-classic-bundle - …
  composer.json
  src/Kernel.php
Labels: Task

#466 [Improvemnet]: use write_target
  config/config.yaml
Labels: Improvement

#469 [Task]: Adapt improvements for system settings
  var/config/system.template.yaml
Labels: Task

#470 [Task] Remove columns from dump
  dump/data-1-documents_page.sql
  dump/data-1-documents_printpage.sql
  dump/data-1-documents_snippet.sql
  dump/data-1-email_blacklist.sql
Labels: Task

#471 [Task]: Fix Demo Gotenberg
  composer.json
  config/config.yaml
  docker-compose.yaml
Labels: Task

#472 Adapt AdminBundle decouple changes
  composer.json
  config/packages/security.yaml
Labels: Task
