Repository pimcore/demo, pull requests merged in 2023-09, with the labels that each got.

#541 Refactor custom report Workflow_Done-All
  dump/data-1-settings_store.sql
Labels: Improvement

#543 Fix demo bo display
  src/Controller/ProductController.php
Labels: Bug

#533 Update definitions
  var/classes/definition_AccessoryPart.php
  var/classes/definition_BodyStyle.php
  var/classes/definition_Car.php
  var/classes/definition_Category.php
  var/classes/definition_Customer.php
  var/classes/definition_CustomerSegment.php
  var/classes/definition_CustomerSegmentGroup.php
  var/classes/definition_Event.php
  var/classes/definition_FilterDefinition.php
  var/classes/definition_LinkActivityDefinition.php
  var/classes/definition_Manufacturer.php
  var/classes/definition_News.php
  var/classes/definition_OfferToolCustomProduct.php
  var/classes/definition_OfferToolOffer.php
  var/classes/definition_OfferToolOfferItem.php
  var/classes/definition_OnlineShopOrder.php
  var/classes/definition_OnlineShopOrderItem.php
  var/classes/definition_OnlineShopTaxClass.php
  var/classes/definition_OnlineShopVoucherSeries.php
  var/classes/definition_OnlineShopVoucherToken.php
  var/classes/definition_TermSegmentBuilderDefinition.php
  var/classes/fieldcollections/FilterCategory.php
  var/classes/fieldcollections/FilterCategoryMultiselect.php
  var/classes/fieldcollections/FilterInputfield.php
  var/classes/fieldcollections/FilterMultiRelation.php
  var/classes/fieldcollections/FilterMultiSelect.php
  var/classes/fieldcollections/FilterMultiSelectFromMultiSelect.php
  var/classes/fieldcollections/FilterNumberRange.php
  var/classes/fieldcollections/FilterNumberRangeSelection.php
  var/classes/fieldcollections/FilterRelation.php
  var/classes/fieldcollections/FilterSelect.php
  var/classes/fieldcollections/FilterSelectFromMultiSelect.php
  var/classes/fieldcollections/NewsCars.php
  var/classes/fieldcollections/NewsLinks.php
  var/classes/fieldcollections/NewsText.php
  var/classes/fieldcollections/OrderByFields.php
  var/classes/fieldcollections/OrderPriceModifications.php
  var/classes/fieldcollections/PaymentInfo.php
  var/classes/fieldcollections/PricingRule.php
  var/classes/fieldcollections/SimilarityField.php
  var/classes/fieldcollections/TaxEntry.php
  var/classes/fieldcollections/VoucherTokenTypePattern.php
  var/classes/fieldcollections/VoucherTokenTypeSingle.php
  var/classes/objectbricks/Bodywork.php
  var/classes/objectbricks/Dimensions.php
  var/classes/objectbricks/Engine.php
  var/classes/objectbricks/PaymentProviderPayPalSmartButton.php
  var/classes/objectbricks/SaleInformation.php
  var/classes/objectbricks/Transmission.php
Labels: Task

#542 [Tests]: Add strategy matrix to cover all the versions and mysql engine
  .github/ci/files/docker-compose.yaml
  .github/workflows/pimcore-demo.yml
Labels: Task
