Repository pimcore/demo, pull requests merged in 2023-03, with the labels that each got.

#425 Remove metadata column from demo dump
  dump/data-1-documents_page.sql
Labels: Task

#431 [Task]: Substitute ForceInheritance::run with DataObject\Service::useInheritedValues
  src/CustomerManagementFramework/SegmentBuilder/ProductInterestSegmentBuilder.php
  src/Model/Product/AdminStyle/Car.php
  src/Model/Product/CalculatedValue/AccessoryPartName.php
  src/Website/LinkGenerator/NewsLinkGenerator.php
  src/Website/LinkGenerator/ProductLinkGenerator.php
  src/Website/Tool/ForceInheritance.php
Labels: Task

#435 Language switcher support for object with detail page.
  src/Twig/Extension/LanguageSwitcherExtension.php
Labels: Bug

#436 [Task]: Prioritize EcommerceFrameworkBundle over PersonalizationBundle
  config/bundles.php
Labels: Task

#430 [System Settings] Change valid_languages format
  var/config/system.template.yaml
Labels: Task

#438 Use Symfony Runtime
  bin/console
  composer.json
  public/index.php
Labels: Task

#433 [Task]: Chromium in Docker
  composer.json
  config/config.yaml
  docker-compose.yaml
  dump/data-1-settings_store.sql
Labels: Task

#443 [Task]: Change LinkGenerator param type to object
  src/Website/LinkGenerator/CategoryLinkGenerator.php
  src/Website/LinkGenerator/NewsLinkGenerator.php
  src/Website/LinkGenerator/ProductLinkGenerator.php
Labels: Task

#446 [Task] Down containers before running docker-compose up again
  .github/workflows/pimcore-demo.yml
Labels: Task

#442 [Improvement]: Add TinymceBundle to bundle.php
  config/bundles.php
Labels: Improvement

#440 Re-enable csp headers
  config/config.yaml
Labels: Improvement

#448 Adapt Admin Bundle refactorings
  src/EventListener/PimcoreAdminListener.php
Labels: Task

#451 Require refactored pimcore bundles
  composer.json
Labels: Task
