Repository pimcore/demo, pull requests merged in 2023-01, with the labels that each got.

#383 [Task]: Remove obsolete adminer regex condition
  .docker/nginx.conf
Labels: Task

#387 Made content and cart thumbnails downloadable by default
  dump/data-1-settings_store.sql
Labels: Improvement

#386 Allow only actual products in Product Teasers
  src/Controller/ProductController.php
  templates/areas/product-teaser/view.html.twig
Labels: Improvement

#390 CategoryFilterExtension: Fix array_filter
  src/Twig/Extension/CategoryFilterExtension.php
Labels: Bug

#391 [Model] Product - Change return type hints as per CheckoutableInterface changes
  src/Model/Product/AbstractProduct.php
  src/Model/Product/AccessoryPart.php
  src/Model/Product/Car.php
Labels: Task

#394 [Task]: Followup PhpStan level 6: params/return type changes
  src/Ecommerce/IndexService/SegmentGetter.php
  src/Kernel.php
  src/Sitemaps/CategoryGenerator.php
  src/Sitemaps/NewsGenerator.php
  src/Sitemaps/ProductGenerator.php
Labels: Task

#393 [Task] Enable PimcoreSeoBundle in config/bundles.php
  config/bundles.php
  dump/data-0-bootstrap.sql
  dump/data-1-settings_store.sql
Labels: Task

#396 [Task] Adding post installation check
  .github/workflows/pimcore-demo.yml
Labels: Task

#401 [Task]: Activate CustomReportsBundle in demo and check custom report configuration for workflows
  config/bundles.php
  dump/data-1-settings_store.sql
Labels: Task

#406 [Task]: Fix return native `void`
  src/Ecommerce/Cart/PriceModificator/Shipping.php
Labels: Task
