Repository pimcore/demo, pull requests merged in 2023-10, with the labels that each got.

#546 Improve: change delete cart item to POST
  src/Controller/CartController.php
  templates/cart/cart_listing.html.twig
Labels: Security

#549 Bump requirements for 11.1 release
  composer.json
Labels: Task

#550 Remove unused permissions tag_snippet_management and piwik_ from User Permissions
  dump/data-1-users_permission_definitions.sql
Labels: Bug

#551 Add example for select options
  dump/data-0-bootstrap.sql
  dump/data-1-object_query_EV.sql
  dump/data-1-object_store_EV.sql
  dump/data-1-users_permission_definitions.sql
  var/classes/definition_Event.php
  var/config/select_options/EventStatus.yaml
Labels: New Feature

#552 Add example for Area Brick
  config/services.yaml
  src/MyAreaBricks/Custom/Areabricks/Validity.php
  templates/areas/validity/view.html.twig
  templates/content/default.html.twig
  templates/default/events.html.twig
Labels: Task
