Repository pimcore/demo, pull requests merged in 2024-10, with the labels that each got.

#601 Prepare 2024.3
  composer.json
Labels: Task

#602 Activate personalization
  config/config.yaml
Labels: Bug, Improvement

#603 [Task]: Workaround create project
  README.md
  composer.json
Labels: Task, Pimcore:ToDo
