Repository pimcore/demo, pull requests merged in 2024-07, with the labels that each got.

#582 [Task]: Fix dump
  dump/data-0-bootstrap.sql
  dump/data-1-assets.sql
  dump/data-1-documents_editables.sql
  dump/data-1-documents_page.sql
  dump/data-1-documents_printpage.sql
  dump/data-1-documents_snippet.sql
  dump/data-1-gridconfigs.sql
  dump/data-1-notes.sql
  dump/data-1-notes_data.sql
  dump/data-1-object_brick_query_Dimensions_CAR.sql
  dump/data-1-object_brick_query_Engine_CAR.sql
  dump/data-1-object_brick_query_SaleInformation_AP.sql
  dump/data-1-object_brick_query_SaleInformation_CAR.sql
  dump/data-1-object_brick_store_Dimensions_CAR.sql
  dump/data-1-object_brick_store_Engine_CAR.sql
  dump/data-1-object_brick_store_SaleInformation_AP.sql
  dump/data-1-object_brick_store_SaleInformation_CAR.sql
  dump/data-1-object_query_CU.sql
  dump/data-1-object_relations_2.sql
  dump/data-1-object_relations_AP.sql
  dump/data-1-object_relations_CA.sql
  dump/data-1-object_relations_CAR.sql
  dump/data-1-object_relations_CU.sql
  dump/data-1-object_relations_EF_FD.sql
  dump/data-1-object_relations_EF_OSO.sql
  dump/data-1-object_relations_EF_OSOI.sql
  dump/data-1-object_relations_EF_OSVT.sql
  dump/data-1-object_relations_EV.sql
  dump/data-1-object_relations_NE.sql
  dump/data-1-search_backend_data.sql
  dump/data-1-settings_store.sql
  dump/data-1-translations_admin.sql
  dump/data-1-translations_messages.sql
  dump/data-1-users_permission_definitions.sql
  dump/data-2-views.sql
Labels: Improvement

#568 docker-compose.yaml: use PHP 8.3
  .github/workflows/pimcore-demo.yml
  README.md
  docker-compose.yaml
Labels: Improvement, Pimcore:ToDo

#578 Add platform-version
  .github/workflows/pimcore-demo.yml
  README.md
  composer.json
Labels: Task

#583 [Task] Switch to generic execution engine
  .docker/supervisord.conf
  .github/workflows/pimcore-demo.yml
  config/bundles.php
  dump/data-0-bootstrap.sql
  dump/data-1-settings_store.sql
  dump/data-1-users_permission_definitions.sql
Labels: Task

#585 Avoid integrity constraint violation on translations_admin table
  dump/data-1-translations_admin.sql
Labels: Bug

#590 Remove hardcoded db names in dumps
  .github/workflows/pimcore-demo.yml
  dump/data-0-bootstrap.sql
Labels: Bug

#589 Remove container_name directive
  docker-compose.yaml
Labels: Bug

#586 Add doctrine session handler config + db schema
  config/services.yaml
  dump/data-0-bootstrap.sql
Labels: Bug
