Repository pimcore/demo, pull requests merged in 2024-04, with the labels that each got.

#565 11.x docker compose update
  config/config.yaml
  docker-compose.yaml
Labels: Pimcore:ToDo

#572 Update .gitignore
  .gitignore
Labels: Pimcore:ToDo

#574 Conflict with twig/twig 3.9.0 || 3.9.1
  composer.json
Labels: Bug

#575 Conflict with twig/twig ^3.9.0
  composer.json
Labels: Bug

#577 [Task]: Update SECURITY.md
  SECURITY.md
Labels: Task, Pimcore:ToDo
