Repository pimcore/demo, pull requests merged in 2024-12, with the labels that each got.

#610 [Task]: Integrate Quill Bundle
  composer.json
  config/bundles.php
  templates/snippets/standard-teaser.html.twig
Labels: Improvement, Pimcore:ToDo, Pimcore:Priority

#604 [Task] Add open-search config for ecommerce framework
  composer.json
  config/ecommerce/base-ecommerce.yaml
  config/ecommerce/open-search.yaml
Labels: Task, Pimcore:ToDo

#612 Prepare 2024.4
  composer.json
Labels: Task
